on:
  workflow_dispatch

permissions:
  contents: read

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Set up Python
          uses: actions/setup-python@v3
          with:
            python-version: '3.12'
        - name: Install dependencies
          run: pip install pyinstaller pandas
        - name: Build exe
          uses: sayyid5416/pyinstaller@v1
          with:
            # python_ver: '3.12'
            spec: 'R3shujugengxin.py'
            upload_exe_with_name: 'R3shuju'
            options: --onefile, --name 'R3shuju'
            
